// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVWF1tOaNDMs5NWB9bAAIz9-j0knv4zNQ',
    appId: '1:919093364183:web:be728ae78d91ba16447792',
    messagingSenderId: '919093364183',
    projectId: 'susu-e8cd2',
    authDomain: 'susu-e8cd2.firebaseapp.com',
    storageBucket: 'susu-e8cd2.appspot.com',
    measurementId: 'G-4HKXMFEZ26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2KIqRTikoTFMg-M7dYq9I4mQ9I5jwEZc',
    appId: '1:919093364183:android:c351c8377f4a6c95447792',
    messagingSenderId: '919093364183',
    projectId: 'susu-e8cd2',
    storageBucket: 'susu-e8cd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfkjEyucSVkB7k5VpfcEI19xlf7sNXNk4',
    appId: '1:919093364183:ios:b6d3b83b3e43974d447792',
    messagingSenderId: '919093364183',
    projectId: 'susu-e8cd2',
    storageBucket: 'susu-e8cd2.appspot.com',
    iosClientId:
        '919093364183-k51ahtd741510i3drhoqme15taciasba.apps.googleusercontent.com',
    iosBundleId: 'com.techgeometry.susu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfkjEyucSVkB7k5VpfcEI19xlf7sNXNk4',
    appId: '1:919093364183:ios:7fdbc9272e53c9ad447792',
    messagingSenderId: '919093364183',
    projectId: 'susu-e8cd2',
    storageBucket: 'susu-e8cd2.appspot.com',
    iosClientId:
        '919093364183-j1nd3gj8d6smb2jrf3akjos061j7sbcc.apps.googleusercontent.com',
    iosBundleId: 'com.techgeometry.susu.RunnerTests',
  );
}
