class StorageConstant {
  StorageConstant._();
  static const isGameShow = "isGameShow";
  static const isLoggedIn = "isLoggedIn";
  static const id = "id";
  static const username = "username";
  static const phone = "phone";
  static const pnotice = "pnotice";
  static const notice1 = "notice1";
  static const money = "money";
  static const phonepe = "phonepe";
  static const paytm = "paytm";
  static const gpay = "gpay";
  static const name = "name";
  static const account_number = "account_number";
  static const ifsc = "ifsc";
  static const play = "play";
  static const active = "active";
  static const live = "live";
  static const bidJodi = "Jodi";
  static const bidander = "ander";
  static const bidbahar = "bahar";
  static const bidquick = "quickcross";
  static const dob = "dob";
  static const email = "email";
  static const user_type = "user_type";
  static const height = "height";
  static const weight = "weight";
  static const gender = "gender";
  static const point = "point";
  static const lab = "lab";
  static const upcoming = "upcoming";
  static const today = "today";
  static const history = "history";
  static const userStatus = "user_status";
  static const lastOrderDate = "last_order_date";
  static const firstTimeUser = "first_time_user";
  // `profile_lock`, `new_order_lock`, `next_date`
  static const profile_lock = "profile_lock";
  static const new_order_lock = "new_order_lock";
  static const next_date = "next_date";
}
